### ISSUE TITLE
bloomfilter.from_base64() will get error

### ISSUE THREAD

**Issue by zoeylee02** [prashnts/pybloomfiltermmap3#5]
Here is error message after generating bloom filter from base64.

```
>>> from pybloomfilter import BloomFilter
>>> f1 = BloomFilter(100, 0.01, '/tmp/b01.bloom')
>>> [f1.add(x) for x in range(100)]
>>> h1 = f1.to_base64()
>>> f2 = BloomFilter.from_base64('/tmp/b02.bloom',  h1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/pybloomfilter.pyx", line 330, in pybloomfilter.BloomFilter.from_base64 (src/pybloomfilter.c:7223)
    return cls.open(filename)
  File "src/pybloomfilter.pyx", line 334, in pybloomfilter.BloomFilter.open (src/pybloomfilter.c:7321)
    return cls(cls.ReadFile, 0.1, filename, 0)
  File "src/pybloomfilter.pyx", line 79, in pybloomfilter.BloomFilter.__cinit__ (src/pybloomfilter.c:1901)
    raise ValueError("Invalid %s file: %s" %
ValueError: Invalid BloomFilter file: /tmp/b02.bloom
>>> f2 = BloomFilter.from_base64(b'/tmp/b02.bloom',  h1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/pybloomfilter.pyx", line 330, in pybloomfilter.BloomFilter.from_base64 (src/pybloomfilter.c:7223)
    return cls.open(filename)
  File "src/pybloomfilter.pyx", line 334, in pybloomfilter.BloomFilter.open (src/pybloomfilter.c:7321)
    return cls(cls.ReadFile, 0.1, filename, 0)
  File "src/pybloomfilter.pyx", line 73, in pybloomfilter.BloomFilter.__cinit__ (src/pybloomfilter.c:1800)
    filename.encode(),
AttributeError: 'bytes' object has no attribute 'encode'
```

Here is what I modified.
```
def to_base64(self):
        self._assert_open()
        filename=self.name.decode()
        bfile = open(filename, 'rb')
        fl_content = bfile.read()
        result = base64.b64encode(zlib.compress(base64.b64encode(zlib.compress(fl_content, 9))))
        bfile.close()
        return result
```

Get base64 from a file by bytes, then it's work after generating bloom filter from base64.

**Comment by zoeylee02** [comment]
Not sure it's correct or not?

**Comment by prashnts** [comment]
Hi! Thanks for the detailed issue. My apologies, I’d been inactive for a while and missed this issue. 

From the looks of it, it seems while porting to python 3 from the original work by @axiak, I missed changing the encoding from latin to utf-8 (which is default in Py3). Quick look at source [1] seems to confirm this. I’ll have a look.

[1] https://github.com/prashnts/pybloomfiltermmap3/blob/master/src/pybloomfilter.pyx#L318

**Comment by prashnts** [comment]
In your implementation of “to_base64”, since you write to b64 *without* explicitly specifying the encoding, it works due to utf-8 being default in c bindings for py3. So, yes! Your solution looks correct to me.
