### ISSUE TITLE
Error using to_bases64

### ISSUE THREAD

**Issue by relinda2019** [prashnts/pybloomfiltermmap3#51]
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/relinda/PycharmProjects/GEELY/geeFedScope/test_22.py", line 9, in <module>
    base64_bytes = bloom_filter.to_base64()
  File "src/pybloomfilter.pyx", line 521, in pybloomfilter.BloomFilter.to_base64
  File "src/pybloomfilter.pyx", line 290, in pybloomfilter.BloomFilter.filename.__get__
  File "src/pybloomfilter.pyx", line 266, in pybloomfilter.BloomFilter._name
NotImplementedError: Cannot access .name on an in-memory BloomFilter

How to solve it? Very thankful!!

**Comment by prashnts** [comment]
Your filter is in-memory, and it's mentioned in Readme that in-memory filters cannot be persisted (yet).
